# Generated by Django 4.1.2 on 2022-10-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeloconsigoStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teloconsigostore',
            table=None,
        ),
    ]
