# Generated by Django 4.1.2 on 2022-10-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeloconsigoStore', '0002_alter_teloconsigostore_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teloconsigostore',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teloconsigostore',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teloconsigostore',
            name='identification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teloconsigostore',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teloconsigostore',
            name='phone_Number',
            field=models.CharField(max_length=100),
        ),
    ]
